apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-s3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-s3-app
  template:
    metadata:
      labels:
        app: flask-s3-app
    spec:
      containers:
      - name: flask-s3-app
        image: flask-s3-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "your-aws-access-key-id"
        - name: AWS_SECRET_ACCESS_KEY
          value: "your-aws-secret-access-key"
        - name: BUCKET_NAME
          value: "your-bucket-name"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-s3-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flask-s3-app
